FROM python:3.8.7-slim

COPY docker/requirements.txt /app/

# install
RUN echo "==> Installing ..."  && \
    apt-get update && \
    apt-get install -y python3-pip gcc curl wget git && \
    # pip3 install --no-cache-dir --upgrade pip -i http://pypi.douban.com/simple --trusted-host pypi.douban.com && \
    # pip3 install --no-cache-dir -r /app/requirements.txt -i http://pypi.douban.com/simple --trusted-host pypi.douban.com --no-deps && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r /app/requirements.txt --no-deps && \
    echo "==> Clean up..."  && \
    apt-get clean  && \
    rm -rf /var/lib/apt/lists/*  && \
    apt-get remove --auto-remove -y python3-pip

COPY /codegen_export_onnx.py /app/
COPY /codegen_onnx_inference.py /app/
COPY /web.py /app/
COPY /model_prepare.sh /app/
COPY /logger.py /app/
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
WORKDIR /app/

RUN echo "==> Preparing Model ..."  && \
    cd /app/ && \
    bash model_prepare.sh

COPY /docker/entrypoint.sh /app/entrypoint.sh

CMD ["sh", "entrypoint.sh"]