name: Publish fastgpt ⚡ to PyPI

on: push

jobs:
  build-pypi-publish:
    name: Build and Publish fastgpt ⚡ to PyPI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build a binary wheel and a source tarball
        run: >-
          python setup.py sdist
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@main
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}